### ISSUE TITLE
Delicious Brains Year In Review

### ISSUE THREAD

**Issue by polevaultweb** [igorbenic/year-in-review#10]
Title*: 2020 Year in Review: Business in the Front, Business in the Back
Author*: Brad Touesnard
URL*: https://deliciousbrains.com/2020-year-in-review/
Thumb (url): https://cdn.deliciousbrains.com/content/uploads/2021/01/07093223/2020-year-review-featured-img-100x100.jpg
Categories: wordpress, plugin, business
Year*: 2020

Title*: 2019 Year in Review: Double the Products, Double the Fun
Author*: Brad Touesnard
URL*: https://deliciousbrains.com/2019-year-in-review/
Thumb (url): https://cdn.deliciousbrains.com/content/uploads/2020/01/08100836/2019-year-review-100x100.jpg
Categories: wordpress, plugin, business
Year*: 2019

**Comment by igorbenic** [comment]
Added :)
