### ISSUE TITLE
Transparency Report #12: burning rubber for a change

### ISSUE THREAD

**Issue by andreiungurianu** [igorbenic/year-in-review#13]
Title*: Transparency Report #12: burning rubber for a change
Author*: Pixelgrade
URL*: https://pixelgrade.com/upstairs/transparency-report-12/
Thumb (url): https://pixelgrade.com/wp-content/uploads/2021/02/transparency-report-12-featured-1.png
Categories wordpress, company, revenue
Year* 2020

**Comment by igorbenic** [comment]
Hi @andreiungurianu sorry for such a late response. I've added it right now.
