### ISSUE TITLE
Kyle Maurer's 2020 year in review

### ISSUE THREAD

**Issue by brashrebel** [igorbenic/year-in-review#2]
Title: My 2020 Year in Review
Author: Kyle Maurer
URL: http://kyleblog.net/2021/01/my-2020-year-in-review/
Thumb (url): https://2xwbo98xbul2e3ai3q6sec13-wpengine.netdna-ssl.com/wp-content/uploads/sites/6/2021/01/2020-08-07-15.12.28-1-scaled-e1610489662138-768x650.jpg
Categories: Personal, WordPress, Life
Year: 2020

**Comment by igorbenic** [comment]
Thank you @brashrebel :) Added.
