### ISSUE TITLE
Year in Review for PublishPress

### ISSUE THREAD

**Issue by stevejburge** [igorbenic/year-in-review#4]
Title*: PublishPress 2020: The Year Everything Doubled
Author*: Steve Burge
URL*: https://publishpress.com/blog/publishpress-2020/
Thumb (url): https://publishpress.com/wp-content/uploads/2021/01/publishpress-2020.jpg
Categories
Year* 2020

**Comment by igorbenic** [comment]
Added. Thanks @stevejburge

**Comment by stevejburge** [comment]
Thanks for doing this @igorbenic
