### ISSUE TITLE
WPManageNinja Year in Review

### ISSUE THREAD

**Issue by dearsadiq** [igorbenic/year-in-review#5]
Title*: WPManageNinja in Numbers: Looking Back to 2020
Author*: Shahjahan Jewel
URL*: https://wpmanageninja.com/wpmanageninja-year-in-review-2020/
Thumb (url): https://d1klenmqvfdv9g.cloudfront.net/wp-content/themes/wpmanageninja/assets/img/wpmanageninja_logo.svg
Categories: wordpress, business, profit, company, plugins, plugin
Year*: 2020

**Comment by igorbenic** [comment]
Hi @dearsadiq, added! Congrats on exceeding your growth target by 50%!

**Comment by dearsadiq** [comment]
Thank you @igorbenic. we were working from home but we never forgot what our customers want. We'd love to continue with the same pace or more.
