### ISSUE TITLE
Please include Barn2's year in review in your article

### ISSUE THREAD

**Issue by Barn2** [igorbenic/year-in-review#6]
Title*: Barn2's 2020 Year in Review
Author*: Katie Keith
URL*: https://barn2.co.uk/2020-year-in-review/
Thumb (url): https://barn2.co.uk/wp-content/uploads/2020/12/Barn2-Year-In-Review-2020.png
Categories
Year*: 2020

**Comment by igorbenic** [comment]
Hi @Barn2, added! Cheers on growing your team and new plugins :)
