### ISSUE TITLE
flowdee's 2020 Year in Review

### ISSUE THREAD

**Issue by flowdee** [igorbenic/year-in-review#7]
Hey @igorbenic, would love to submit my very first review post to your cool project 😄 

**Title**: 2020 Year in Review – First time for me, Yay!
**Author**: flowdee
**URL**: https://flowdee.dev/blog/2020-year-in-review/
**Thumb** (url): https://flowdee.dev/wp-content/uploads/2021/01/flowdee-thumbnail-2020-year-in-review.jpg
**Categories**: wordpress, business, personal, plugins
**Year**: 2020

**Comment by igorbenic** [comment]
Hi @flowdee, added :) Thanks!

**Comment by flowdee** [comment]
Thanks Igor!
