### ISSUE TITLE
Fluent Forms Year in Review 2020

### ISSUE THREAD

**Issue by dearsadiq** [igorbenic/year-in-review#8]
Author*: Sadiq Ahmad
URL*: https://wpfluentforms.com/fluent-forms-year-in-review-2020/
Thumb (url): https://wpfluentforms.com/wp-content/uploads/2019/11/cropped-screenshot-try.gutendev.com-2019.11.08-12_18_01-11-65x65.png
Categories: wordpress, plugin, business
Year*: 2020

**Comment by igorbenic** [comment]
Added :)
